### ISSUE TITLE
I'm using latest version of Chrome Version 65.0.3325.181 (Official Build) (64-bit)on Mac Sierra and I cannot log in.  I put in the username and password and it just sits there looping.  

### ISSUE THREAD

**Issue by coolpillows** [moonlightwork/bug-tracker#7] opened 2018-03-27 13:23 UTC
<img width="1334" alt="screen shot 2018-03-27 at 9 22 24 am" src="https://user-images.githubusercontent.com/15839032/37970059-78670cda-31a0-11e8-92a9-45330bf333fe.png">
If you use moonlightwork.com, you can use this repo to report and track bugs in the application, or to browse known issues. If the bug is security-related, please send a private report to team@moonlightwork.com.

### Which browser are you using?

If applicable - please share a link from http://www.whatsmybrowser.org

**Comment by philipithomas** [comment] 2018-03-27 14:29
Hi @coolpillows - we use Invisible Recaptcha on that page. Is your browser loading anything such as Ghostery that may be blocking the loading of recaptcha? 

Can you try logging in in a private browsing window and see if that works?

**Comment by coolpillows** [comment] 2018-03-27 14:34
the private window worked.  i could see the Recapthcha and was activating that properly.  don't think i use Ghostery, but I use the Privacy Badger plug in and had turned that off to now avail.  but no worries, I'm in on incognito.  this is something to look into of course.  :)

**Comment by philipithomas** [comment] 2018-03-27 14:49
@coolpillows Sounds like it's a plugin affecting log-in, if it is working in incognito mode.

Can you help us figure out which plugin is causing problems? If you disable privacy badger and hard refresh the page, does it work?

**Comment by philipithomas** [comment] 2018-03-28 00:52
@coolpillows i'm closing this issue for now because I cannot reproduce, and it seems based on your testing in a private browser window that it may be related to browser plugins. 

If you can help us debug the browser plugins that may be causing this, please re-open or email us!

**Closed** 2018-03-28 00:55 UTC
Labels: cannot reproduce
